version: "3.8"

services:
  mysqldb:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyer_bd
      - MYSQL_ROOT_HOST=%  # Allows root login from any host
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql_network

  tp-foyer:
    depends_on:
      - mysqldb
    image: autismusprime/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/foyer_bd?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    networks:
      - mysql_network

volumes:
  db:

networks:
  mysql_network:
    driver: bridge
